search: "ğŸ”"
lyrics: "ğŸ“ƒ"
arrow_left: "â—€ï¸"
arrow_right: "â–¶ï¸"
double_arrow_left: "âª"
double_arrow_right: "â©"
music_resume: "â–¶ï¸"
music_pause: "â¸ï¸"
music_loop: "ğŸ”"
music_next: "â­ï¸"
music_previous: "â®ï¸"
note_stalled: "â³"
note_finished: "âœ…"
note_ongoing: "ğŸ”„"
note_remove: "âŒ"
note_unbegan: "ğŸš«"
